baseURL = "https://studentcybermooc.github.io/cybermooc/"
title = "Cyber MOOC"
theme = "cybermooc_theme"

[params]
    description = "ENSIBS Student Cyber MOOC"
    githubRepo = "studentcybermooc/cybermooc"